android-extra: Enable HID_SONY, disable ANDROID_LOW_MEMORY_KILLER
ERROR: files are incompatible: Runtime info and framework compatibility
matrix are incompatible: No compatible kernel requirement found (kernel
FCM version = 5).
For kernel requirements at matrix level 5, Kernel config errors:
    For config CONFIG_ANDROID_LOW_MEMORY_KILLER, value = y but required n
    Missing config CONFIG_HID_SONY

https://source.android.com/docs/core/perf/lmkd#using-userspace-lmkd

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>