android-base: Add missing configs to satisfy FCM
ERROR: files are incompatible: Runtime info and framework
compatibility matrix are incompatible: No compatible kernel
requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config
errors:
    Missing config CONFIG_HAVE_MOVE_PMD
    Missing config CONFIG_HAVE_MOVE_PUD
    Missing config CONFIG_USERFAULTFD

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>